### ISSUE TITLE
Incompatibility with go modules

### ISSUE THREAD

**Issue by rgritti** [dennwc/gotrace#1]
I have a compatibility problem with the go modules:
```
filters/svgtrace.go:12:2: unknown import path "github.com/dennwc/gotrace": unzip /home/xxx/go/pkg/mod/cache/download/github.com/dennwc/gotrace/@v/v0.0.0-20151111213338-0306f421d687.zip: malformed file path "aux.go": disallowed path element "aux.go"
```
as [microsoft](https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file) says:

> - Do not use the following reserved names for the name of a file:
>CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt is not recommended. For more information, see Namespaces.

it should be enough to rename the file aux.go

see [here](https://github.com/golang/vgo/blob/master/vendor/cmd/go/internal/module/module.go#L229) for further details

**Comment by dennwc** [comment]
Should be fixed by #2
