### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bep** [dennwc/gotrace#3]
Hey, and thanks for this great libray,

I'm maintaining Hugo and have been looking for a library like this to integrate into the image processing. But that would need to be open source. Could you add a suitable license to this repository?

Thanks!

**Comment by dennwc** [comment]
[Done](https://github.com/dennwc/gotrace/commit/a0f953fb256c33c1d0a7cff8d6c88711d4dbb8ee)! Hope you would find it useful :)

**Comment by icholy** [comment]
@dennwc you need to tag a release which includes the LICENSE. It's currently not showing up in the [pkgsite](https://pkg.go.dev/github.com/dennwc/gotrace)

**Comment by icholy** [comment]
@dennwc ping

**Comment by dennwc** [comment]
@icholy done! Sorry for the delay.

**Comment by icholy** [comment]
Thanks!
