### ISSUE TITLE
bug convert png to svg

### ISSUE THREAD

**Issue by jilieryuyi** [dennwc/gotrace#4]
src image
![0](https://user-images.githubusercontent.com/2398119/150904835-d73bb90d-89e8-421e-98e6-3521081e279d.png)

got svg
 
![0 png](https://user-images.githubusercontent.com/2398119/150904871-f834e9b6-c341-4ad9-903f-ae305261abc5.svg)

**Comment by dennwc** [comment]
Thank you for reporting it!

There's now [cxgo](https://github.com/gotranspile/cxgo) tool that can convert C to Go directly, and I already have a config for [converting Potrace](https://github.com/gotranspile/cxgo/tree/main/examples/potrace). So when I get a bit of free time, I will make a new repository that will pull the code directly from original Potrace and convert it to Go with cxgo.

**Comment by jilieryuyi** [comment]
> Thank you for reporting it!
> 
> There's now [cxgo](https://github.com/gotranspile/cxgo) tool that can convert C to Go directly, and I already have a config for [converting Potrace](https://github.com/gotranspile/cxgo/tree/main/examples/potrace). So when I get a bit of free time, I will make a new repository that will pull the code directly from original Potrace and convert it to Go with cxgo.

thank you

**Comment by dennwc** [comment]
First preview of converted library: https://github.com/gotranspile/gotrace
