### ISSUE TITLE
Incorrect output: Jagged outlines and no holes

### ISSUE THREAD

**Issue by jscheithe** [dennwc/gotrace#5]
Hi, thanks a lot for your work on this package.

I tried to reproduce tracing the sample image from the readme. 
The outlines look jagged and it seems that there are no holes at all in the image.

<img src="https://user-images.githubusercontent.com/9197807/205323402-b18a71ba-d85d-48a7-9fd5-01492119d976.svg" width="400"><img src="https://user-images.githubusercontent.com/9197807/205323336-437ade1f-01de-463b-aaa0-c2393bfef30f.png" width="400">

I tried using both `gotrace.Trace` and `gotraceb.Trace`
I'm on Ubuntu 22.04 using WLS2 from a Windows 11 host and I tried both `go1.19.3` and `go1.10`.

When I use the `potrace` command line tool, the output looks fine.

```go
package main

import (
	"fmt"
	"image"
	"image/color"
	_ "image/png"
	"os"

	"github.com/dennwc/gotrace"
	gotraceb "github.com/dennwc/gotrace/bindings"
)

func main() {
	imgPath := "/home/jakob/tmp/potrace/stanford-orig2.png"

	rdr, err := os.Open(imgPath)
	check(err)
	defer rdr.Close()

	img, _, err := image.Decode(rdr)
	check(err)

	thresholdFunc := func(_, _ int, cl color.Color) bool {
		r, g, b, _ := cl.RGBA()
		return r+g+b < 128
	}
	bm := gotrace.NewBitmapFromImage(img, thresholdFunc) 

	paths, err := gotrace.Trace(bm, nil)
	//paths, err := gotraceb.Trace(bm, nil)

	f, err := os.Create("/home/jakob/tmp/trace.svg")
	check(err)
	defer f.Close()

	gotrace.WriteSvg(f, image.Rect(0, 0, img.Bounds().Dx(), img.Bounds().Dy()), paths, "red")
}

func check(err error) {
	if err != nil {
		fmt.Println(err)
		panic(err)
	}
}
```

**Comment by mixicz** [comment]
No holes problem is apparently same as https://github.com/dennwc/gotrace/issues/6, as `WriteSvg()` function does not process the path recursively.

Regarding jagged edges, I suggest to add `Params` struct to `Trace()` call. Default values can be found here https://github.com/dennwc/gotrace/blob/v1.0.3/gotrace.go#L95 and by tweaking them you should get better results (parameters are explained in original potrace library, for example in this document: https://potrace.sourceforge.net/potracelib.pdf, chapter 2.3).

**Comment by dennwc** [comment]
This library is deprecated, so I'm closing this now and will archive the repository. See [gotranspile/gotrace](https://github.com/gotranspile/gotrace) instead. Its output matches potrace 1:1.
