### ISSUE TITLE
WriteSvg() does not process child elements

### ISSUE THREAD

**Issue by mixicz** [dennwc/gotrace#6]
This is in fact same bug as reported in https://github.com/dennwc/gotrace/issues/4. It is caused when image has background (e.g. "white" in https://github.com/dennwc/gotrace/issues/4) as solid and "black" as transparent. Then trace code properly creates rectangle with holes as child elements. But as `WriteSvg()` function completely ignores child paths, result is SVG with just single black rectangle.

Same problem is valid even when background is transparent for objects with holes. 
See this example (face is most visible missing feature):

![Source](https://www.mixi.cz/files/gotrace-i6/test.png)

![Output](https://www.mixi.cz/files/gotrace-i6/out.svg)

**Comment by jscheithe** [comment]
This could be the same as #5, which I have opened. 
I'd be happy if you let me know whenever you find out anything.

**Comment by dennwc** [comment]
As mentioned in #5, I don't have plans for supporting this library.

Instead, can you please try the new one: https://github.com/gotranspile/gotrace ? It converts the original example precisely, so should work for your image as well. It may lack helper functions, comparing to this library, but I plan to add them soon as well.

**Comment by mixicz** [comment]
> Instead, can you please try the new one: https://github.com/gotranspile/gotrace ? It converts the original example precisely, so should work for your image as well. It may lack helper functions, comparing to this library, but I plan to add them soon as well.

I looked at the new repository, but it does not look like drop-in replacement and it still lacks any kind of documentation or examples (it's not even on pkg.go.dev yet). It is significantly more complex project (at least by amount of source files) and I don't have time to study the source to guess proper usage.

Can you please add at least some simple example of bitmap import, trace and svg export?

**Comment by dennwc** [comment]
Here's [an example](https://github.com/gotranspile/gotrace/blob/main/example_test.go) for the new library.

**Comment by mixicz** [comment]
Thanks for the example. After some testing I can confirm that new library does properly export svg with recursively nested paths.

**Comment by dennwc** [comment]
I'm closing this now and will archive the repository. See [gotranspile/gotrace](https://github.com/gotranspile/gotrace).
